require('dotenv').config();

module.exports = {
  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
  GOOGLE_OAUTH_REDIRECT_URL: process.env.GOOGLE_OAUTH_REDIRECT_URL,
  JWT_SECRET: process.env.JWT_SECRET,
  FFMPEG_PATH: process.env.FFMPEG_PATH,
  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME,
};
